name: Install Intel oneAPI

on:
  # Trigger the workflow on push or pull request
  #push:
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-11]
        bitness: [32, 64]
        oneapi: [2021, 2022, 2023]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: find bitness macOS
        if: startsWith(matrix.os, 'macos')
        run:  uname -a && uname -m

      - name: find bitness Windows
        if: startsWith(matrix.os, 'windows')
        run:  wmic os get osarchitecture


      - name: Install Intel oneAPI on macOS for Fortran
        if: startsWith(matrix.os, 'macos')
        run: sudo bash install_oneapi_macos.sh ${{ matrix.oneapi }}

      - name: Install Intel oneAPI on Windows for Fortran
        if: startsWith(matrix.os, 'windows')
        run: cmd.exe "/K" '"install_oneapi_windows.bat" ${{ matrix.oneapi }}'
