name: Install Intel oneAPI

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]
        oneapi: [2021, 2022, 2023]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Intel oneAPI on Windows for Fortran
        if: startsWith(matrix.os, 'windows')
        run: cmd.exe "/K" '"install_oneapi_windows.bat" ${{ matrix.oneapi }}'
