name: Test MEX with mingw

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * 6'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

env:
  LATEST_MINGW: 15

jobs:
  test:
    name: Test MEX with mingw
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-latest]
        matlab: [R2024a, R2024b, R2025a, R2025b, R2026a, latest]
        mingw: [11, 12, 13, 14, 15, latest]
        lang: [Fortran]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      # - name: Remove Visual Studio completely
      #   shell: cmd
      #   if: startsWith(matrix.os, 'windows')
      #   run: |
      #     "C:\Program Files (x86)\Microsoft Visual Studio\Installer\InstallCleanup.exe"

      - name: Remove existing gcc installation
        shell: cmd
        if: startsWith(matrix.os, 'windows')
        run: |
          rmdir "C:\mingw64" /s /q
          rmdir "C:\Strawberry" /s /q


      - name: Install mingw
        shell: bash
        if: startsWith(matrix.os, 'windows')
        run: |
          VERSION="${{ matrix.mingw }}"
          if [ "$VERSION" = "latest" ]; then
            VERSION="${{ env.LATEST_MINGW }}"
          fi
          VERSION="${VERSION}".2.0
          choco install mingw --version=$VERSION -y --no-progress
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH  # mingw 12 and earlier
          echo "C:\ProgramData\mingw64\mingw64\bin" >> $GITHUB_PATH  # mingw 13 and later

      - name: Check gcc and gfortran version
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows')
        run: which gcc && gcc --version && which gfortran && gfortran --version

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3.0.0
        with:
          release: ${{ matrix.matlab }}
          cache: true

      - name: Run the test
        uses: matlab-actions/run-command@v3.1.1
        with:
          command: |
            % 'MW_MINGW64_LOC' should be set to the directory containing bin\gcc.exe and bin\gfortran.exe
            if str2int('${{ matrix.mingw }}') <= 12
                setenv('MW_MINGW64_LOC', 'C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64')
            else
                setenv('MW_MINGW64_LOC', 'C:\ProgramData\mingw64\mingw64')
            end

            lang = '${{ matrix.lang }}';

            fprintf("\n\nTry setting mex up, attempt 0:\n\n");
            mex -v -setup ${{ matrix.lang }}

            fprintf("\n\nTry setting mex up, attempt 1:\n\n");
            try_mex_setup(lang, true);

            fprintf("\n\nTry setting mex up, attempt 2:\n\n");
            mex -v -setup ${{ matrix.lang }}

            fprintf("\n\nTry setting mex up, attempt 3:\n\n");
            try_mex_setup(lang, true);

            fprintf("\n\nTry compiling the official example from MathWorks:\n\n");
            mex('-v', official_mex_example(lang));
            timestwo(1)
