name: Test MEX

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * 6'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test MEX
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022, windows-latest, macos-13] # macos-14 is only for Apple Silicon chip, which needs nagfor
        matlab: [R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, latest]
        oneapi: [2023, 2024, 2025]
        lang: [Fortran, C]

        exclude:
          # Intel oneAPI does not support macOS anymore starting from 2024.
          - os: macos-13
            oneapi: 2024
          - os: macos-13
            oneapi: 2025
          # MATLAB R2021a/21b do not work with the latest gortran
          - os: ubuntu-latest
            matlab: R2021a
          - os: ubuntu-latest
            matlab: R2021b


        # Below R2022a, MEX does not work on windows-latest due to the version of MS Visual Studio;
        # R2022a/b should work according to the documentation of MathWorks and GitHub Actions, but
        # they do not as of March 2022.
          - os: windows-latest
            matlab: R2021a
          - os: windows-latest
            matlab: R2021b
          - os: windows-latest
            matlab: R2022a
          - os: windows-latest
            matlab: R2022b

          - os: windows-2025
            matlab: R2021a
          - os: windows-2025
            matlab: R2021b
          - os: windows-2025
            matlab: R2022a
          - os: windows-2025
            matlab: R2022b

          # OneAPI 2024 is not supported before MATLAB R2024a
          - matlab: R2023a
            oneapi: 2024
          - matlab: R2023b
            oneapi: 2024

          # OneAPI 2025 is not supported before MATLAB R2025a
          - matlab: R2023a
            oneapi: 2025
          - matlab: R2023b
            oneapi: 2025
          - matlab: R2024a
            oneapi: 2025
          - matlab: R2024b
            oneapi: 2025

    steps:
      - name: Check out repository
        uses: actions/checkout@v5.0.0


      - name: Set up gfortran on Linux
        if: startsWith(matrix.os, 'ubuntu')
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: gcc
      - name: Check gfortran version on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: which gcc && gcc --version && which gfortran && gfortran --version

      - name: Install Intel oneAPI on macOS for Fortran
        if: startsWith(matrix.os, 'macos') && matrix.lang == 'Fortran'
        run: sudo bash install_oneapi_macos.sh ${{ matrix.oneapi }}

      - name: Install Intel oneAPI on Windows for Fortran
        if: startsWith(matrix.os, 'windows') && matrix.lang == 'Fortran'
        run: cmd.exe "/K" '"install_oneapi_windows.bat" ${{ matrix.oneapi }}'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.6.0
        with:
          release: ${{ matrix.matlab }}
          cache: true

      - name: Run the test
        uses: matlab-actions/run-command@v2.2.2
        with:
          command: |
            lang = '${{ matrix.lang }}';

            fprintf("\n\nTry setting mex up, attempt 1:\n\n");
            try_mex_setup(lang, true);

            fprintf("\n\nTry setting mex up, attempt 2:\n\n");
            mex -v -setup ${{ matrix.lang }}

            fprintf("\n\nTry setting mex up, attempt 3:\n\n");
            try_mex_setup(lang, true);

            fprintf("\n\nTry compiling the official example from MathWorks:\n\n");
            mex('-v', official_mex_example(lang));
            timestwo(1)
