name: Test MEX

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * 6'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test MEX
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-latest, windows-2019, windows-latest]
        matlab: [R2020a, R2020b, R2021a, R2021b, R2022a, R2022b]
        oneapi: [2021, 2022, 2023]
        lang: [Fortran, C]
        exclude:
          - os: windows-2019
            matlab: R2020a
          - os: windows-2019
            matlab: R2020b
          - os: windows-latest
            matlab: R2020a
          - os: windows-latest
            matlab: R2020b
          - os: windows-latest
            matlab: R2021a
          - os: windows-latest
            matlab: R2021b

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Intel oneAPI on macOS for Fortran
        if: startsWith(matrix.os, 'macos') && matrix.lang == 'Fortran'
        run: sudo bash install_oneapi_macos.sh ${{ matrix.oneapi }}

      - name: Install Intel oneAPI on Windows for Fortran
        if: startsWith(matrix.os, 'windows') && matrix.lang == 'Fortran'
        run: cmd.exe "/K" '"install_oneapi_windows.bat" ${{ matrix.oneapi }}'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.2.3
        with:
          release: ${{ matrix.matlab }}

      - name: Run the test
        uses: matlab-actions/run-command@v1
        with:
          command: |
            lang = '${{ matrix.lang }}';
            try_mex_setup(lang);
            try_mex_setup(lang);
            if strcmpi(lang, 'Fortran')
                mex('-v', fullfile(matlabroot,'extern','examples','refbook','timestwo.F'));
            else
                mex('-v', fullfile(matlabroot,'extern','examples','refbook','timestwo.c'));
            end
            timestwo(1)
