name: Test MEX, Fortran, Windows
# MATLAB R2022b requires Intel OneAPI 2021 with Microsoft Visual Studio 2019.
# Intel OneAPI is installed by windows/install_oneapi_windows.bat, and Microsoft Visual Studio 2019
# is available with windows-2019 but not windows-2022.

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test MEX
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]
        matlab: [latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install Intel oneAPI on Windows
        run: cmd.exe "/K" '".github/scripts/install_oneapi_windows.bat" && powershell'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.1.0
        with:
          release: ${{ matrix.matlab }}

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: |
            setenv('ONEAPI_ROOT', 'C:\Program Files (x86)\Intel\oneAPI');  % Needed.
            mex('-setup', '-v', 'FORTRAN');
            mex('-v', fullfile(matlabroot,'extern','examples','refbook','timestwo.F'));
            timestwo(1)
