name: Test MEX, Windows, Fortran

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Test MEX for Fortran on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        language: [Fortran]
        matlab: [latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install Intel oneAPI on Windows
        shell: bash
        run: windows/install_oneapi_windows.bat

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.1.0
        with:
          release: ${{ matrix.matlab }}

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: |
            setenv('ONEAPI_ROOT', 'C:\Program Files (x86)\Intel\oneAPI');
            mex('-setup', '-v', 'FORTRAN');
            mex('-v', fullfile(matlabroot,'extern','examples','refbook','timestwo.F'));
            timestwo(1);
            delete('timestwo.mex*');
